"""Assemble paper/supplementary_tables.md from the generated Markdown tables (paper/tables/md/s*.md)."""
from pathlib import Path
P = Path(__file__).resolve().parents[1]
MD = P / "tables" / "md"

items = [
 ("S1", "s1_exp1_per_seed", "Readout ladder (E1), per seed. Amplitude circuit, N = 16, 20,153 training records. 'frozen_theta' arms apply a readout to the weights trained with qubit-0 parity; 'global_parity' applied to those weights is a mismatched-decoder control; 'reference/logreg_on_xhat' has no seed variance."),
 ("S2", "s2_exp2_per_seed", "Encoded-state geometry (E2), per seed, N and soft margin C. AUC does not depend on C."),
 ("S3", "s3_exp3_per_seed", "Norm restoration (E3), per seed, from `results/exp3_norm_v2.csv` (exp3b: the unchanged exp3 script re-run with the novel-signature definition of [1]; its 35 rows in common with `exp3_norm.csv` are identical, and it adds the depth control 'vqc_amplitude_4q_reps4_p20'). Row 'auc_of_norm_alone' reports an AUC in the first two numeric columns, not an accuracy. 'vqc_amplitude_4q_p24' is the anchor circuit (identical to the E1 parity row), 'vqc_amplitude_4q_reps4_p20' the same circuit at reps = 4, 'vqc_amplitude+norm_5q_p25' carries the norm on a fifth qubit, 'vqc_shuffled_norm_5q_p25' carries the norm shuffled across records; the last three share reps = 4."),
 ("S4", "s4_exp4_capacity", "Memorisation capacity (E4): training accuracy on labels corrupted with fraction ρ, excess over a signal-only learner, and clean-data metrics (mean over five seeds). Model names carry the parameter count."),
 ("S5", "s5_angle_kernel_vs_gaussian", "Angle-RY fidelity kernel (scale s = 0.25) against a Gaussian kernel with γ = s²/4 = 0.015625, on the E2 subsamples (five seeds). Accuracies are means over seeds."),
 ("S6", "s6_head_shots", "Finite-shot accuracy of the co-trained linear head on the seed-0 angle-encoded circuits (E7), recomputed from the notebook checkpoints. The head coefficients were trained on columns in ascending-bitmask order (single-qubit and two-qubit strings interleaved, global parity last). Assembling the shot-estimated features in the order [single, pair, parity], as the companion notebook does, gives chance-level accuracy; assembling them in the head's own order gives the values used in the paper."),
 ("S7", "s7_depth_replication", "Replication of the depth sweep of [1] (its Table A2) at all five depths with the exact simulator (E6, qubit-0 parity; the reps 1/5/17 rows are identical to E4 at ρ = 0). Mean ± SD over five seeds; Δ in accuracy points; Welch p."),
 ("S8a", "s8a_resources_full", "Transpiled resources of all circuits, both connectivity assumptions. Depth {u,cx} is the gate-set-agnostic depth; depth native uses {cx, rz, sx, x}. Amplitude state preparation: median (range) over 25 real records."),
 ("S8b", "s8b_amp_scaling", "Two-qubit gates and depth of amplitude state preparation against the number of qubits (all-to-all; median of five random real vectors)."),
 ("S10", "s10_exp6_depth_readout", "Depth × readout at the 2,000-record protocol of [1] (E6): RealAmplitudes (reverse_linear) on 4 qubits, amplitude encoding of 16 components, COBYLA budget max(150, 24(reps + 1)). Frozen readouts use the weights of the parity fit; the co-trained head re-optimises the weights. Mean ± SD over five seeds."),
 ("S11", "s11_exp5_all", "Matched encoding comparison (E5), every model and readout, mean ± SD over seeds (single values where only seed 0 exists: the 16-qubit angle circuits, evaluated from the notebook's checkpoints). Both circuit arms: n_local(RY, CX, linear), 3N parameters, COBYLA 400 evaluations, the same 2,000-record training subsample per seed; evaluation on the full internal test split (5,039), KDDTest+ (22,544) and 3,752 novel-signature records."),
]
out = ["# Supplementary Tables (draft)", "",
       "All tables are generated by `paper/analysis/make_tables.py` from `results/*.csv`, `notebook/ckpt/*.npz` and the analysis outputs. "
       "[1] is the control study (Thomos & Andronikos, J. Sens. Actuator Netw. 2026, 15(4), 67).", ""]
log = (P / "tables" / "simulator_verification_log.txt").read_text()
s9 = ["## Table S9 (log)", "", "**Table S9.** Simulator verification against Qiskit, run before the analyses (`verify_fastsim.py`, "
      "`notebook/angle_fast_v2.py`); the dense amplitude-arm ansatz of `exp5_matched_sweep.py` checks itself against Qiskit at "
      "start-up (maximum deviation 5.6 × 10⁻¹⁶).", "", "```", log.strip(), "```", ""]
for tag, name, cap in items:
    if tag == "S10":
        out += s9
    out += [f"## Table {tag}", "", f"**Table {tag}.** {cap}", "", (MD / f"{name}.md").read_text().strip(), ""]
(P / "supplementary_tables.md").write_text("\n".join(out))
print("wrote", P / "supplementary_tables.md", f"({len(out)} lines)")
